### ISSUE TITLE
up to date problem

### ISSUE THREAD

**Issue by DoctorCheese1** [Norbit4/DiscordMc#7]
[22:28:52 ERROR]: Error occurred while enabling DiscordMc v1.0-SNAPSHOT (Is it up to date?)
java.lang.NumberFormatException: The specified ID is not a valid snowflake (discord-rank-id). Expecting a valid long value!
	at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:123) ~[DiscordMc-v1.5.0.jar:?]
	at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59) ~[DiscordMc-v1.5.0.jar:?]
	at net.dv8tion.jda.api.entities.Guild.getRoleById(Guild.java:1458) ~[DiscordMc-v1.5.0.jar:?]
	at pl.norbit.discordmc.discord.DiscordUserService$Rank.<init>(DiscordUserService.java:38) ~[DiscordMc-v1.5.0.jar:?]
	at pl.norbit.discordmc.discord.DiscordUserService.formatConfig(DiscordUserService.java:72) ~[DiscordMc-v1.5.0.jar:?]
	at pl.norbit.discordmc.discord.DiscordUserService.init(DiscordUserService.java:52) ~[DiscordMc-v1.5.0.jar:?]
	at pl.norbit.discordmc.DiscordMc.start(DiscordMc.java:90) ~[DiscordMc-v1.5.0.jar:?]
	at pl.norbit.discordmc.DiscordMc.onEnable(DiscordMc.java:41) ~[DiscordMc-v1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:28:52 INFO]: [DiscordMc] Disabling DiscordMc v1.0-SNAPSHOT
[22:28:52 INFO]: 
[22:28:52 INFO]: ------------[DiscordMC]------------
[22:28:52 INFO]: BYE :(
[22:28:52 INFO]: -----------------------------------

**Comment by DoctorCheese1** [comment]
i downloaded the latest version im on paper 1.20.2 minecraft version
